apiVersion: apps/v1
kind: Deployment
metadata:
  name: multinode-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multinode
  template:
    metadata:
      labels:
        app: multinode
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
