name: Cache Simple Lab

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: my-cache
          key: simple-cache

      - name: Create Cache Directory
        run: mkdir -p my-cache

      - name: Write File
        run: echo "Hello from cache" > my-cache/file.txt

      - name: Show File
        run: cat my-cache/file.txt
