name: Cache Pip Lab

on:
  push:
    branches:
      - main

jobs:
  pip-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache

      - name: Install requests package
        run: pip install requests
