name: Three - Checkout Read File Lab

on:
  push:
    branches:
      - main
  #workflow_dispatch:

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files
        run: ls -R

      - name: Read File
        run: cat hello-world/repo-file.txt
