name: N2 Hello Workflow N2

on:
  push:
    branches:
      - main

jobs:
  N-hello-job-N:
    runs-on: ubuntu-latest

    steps:
      - name: N Say Hello N 
        run: echo "N Hello from GitHub Actions N "

      - name: N Show Date N 
        run: date
        if: failure()
