name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-ci-lab:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-ci-lab:latest

      - name: Setup Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

#      - name: Deploy to Kubernetes
#        run: |
#          #kubectl apply -f k8s/deployment.yaml
#          kubectl apply -f k8s/dep-svc.yaml
#          #kubectl apply -f k8s/service.yaml
      - name: Simulate Kubernetes Deploy
        run: |
           echo "Deploying to Kubernetes..."
           cat k8s/dep-svc.yaml
           echo "Deployment simulated"
