name: Multiple Needs Lab

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "Running Job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: echo "Running Job 2"

  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: echo "Running Job 3 after Job1 and Job2"
