name: Cache Lab

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: cache-folder
          key: my-cache-key

      - name: Create File
        run: |
          mkdir -p cache-folder
          echo "Cache created on $(date)" > cache-folder/file.txt
          cat cache-folder/file.txt
