name: Cache Counter Lab

on:
  push:
    branches:
      - main

jobs:
  cache-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: counter-dir
          key: counter-cache

      - name: Create Directory
        run: mkdir -p counter-dir

      - name: Update Counter
        run: |
          if [ -f counter-dir/count.txt ]; then
            count=$(cat counter-dir/count.txt)
          else
            count=0
          fi
          count=$((count+1))
          echo $count > counter-dir/count.txt
          echo "Counter value is $count"

      - name: Show Counter File
        run: cat counter-dir/count.txt
