name: Cache Lab

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-demo-${{ runner.os }}

      - name: Install something
        run: |
          mkdir -p ~/.cache/demo
          echo "Hello Cache" > ~/.cache/demo/file.txt
          ls ~/.cache/demo
