name: Cache Restore Keys Lab

on:
  push:
    branches:
      - main

jobs:
  cache-restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: cache-folder
          key: app-cache-v1
          restore-keys: |
            app-cache-

      - name: Write File
        run: |
          mkdir -p cache-folder
          echo "Cache restore test - $(date)" > cache-folder/test.txt
          cat cache-folder/test.txt
