name: Blue-Green Deploy (k3s)

on:
  workflow_dispatch:
#  push:
#    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
  workflow_dispatch:

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install k3s
      run: |
        curl -sfL https://get.k3s.io | sh -

        # set kubeconfig
        sudo chmod 644 /etc/rancher/k3s/k3s.yaml
        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

        # wait for cluster
        sleep 20

        # verify
        kubectl get nodes

    - name: Deploy Blue
      run: kubectl apply -f k8s/blue/
      env:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Deploy Green
      run: kubectl apply -f k8s/green/
      env:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Create Service (Blue first)
      run: kubectl apply -f k8s/service.yaml
      env:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Verify Green Pods
      run: kubectl get pods -l version=green
      env:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Switch Traffic to Green
      run: |
        kubectl patch service nginx-service \
        -p '{"spec":{"selector":{"app":"nginx","version":"green"}}}'
      env:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Verify Rollout
      run: kubectl get pods
      env:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml #
