name: ConfigMap Update and Rollout Restart

on:
  workflow_dispatch:

jobs:
  configmap-restart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Create Kind Cluster
      uses: helm/kind-action@v1

    - name: Create ConfigMap
      run: kubectl apply -f k8s/configmap.yaml

    - name: Deploy Application
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl rollout status deployment/myapp-deployment --timeout=180s

    - name: Check APP_COLOR Before Update
      run: |
        POD=$(kubectl get pod -l app=myapp -o jsonpath="{.items[0].metadata.name}")
        kubectl exec $POD -- printenv APP_COLOR

    - name: Update ConfigMap
      run: |
        kubectl create configmap myapp-config \
          --from-literal=APP_COLOR=green \
          -o yaml --dry-run=client | kubectl apply -f -

    - name: Rollout Restart Deployment
      run: |
        kubectl rollout restart deployment/myapp-deployment
        kubectl rollout status deployment/myapp-deployment --timeout=180s

    - name: Check APP_COLOR After Update
      run: |
        POD=$(kubectl get pod -l app=myapp -o jsonpath="{.items[0].metadata.name}")
        kubectl exec $POD -- printenv APP_COLOR

    - name: Show Pods
      run: kubectl get pods -o wide
