name: K8 GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  kubernetes-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Check Kubernetes Cluster
      run: kubectl get nodes

    - name: Create ConfigMap
      run: kubectl apply -f k8s/configmap.yaml

    - name: Create Secret
      run: kubectl apply -f k8s/secret.yaml

    - name: Create Deployment
      run: kubectl apply -f k8s/deployment.yaml

    - name: Create Service
      run: kubectl apply -f k8s/service.yaml

    - name: Verify Resources
      run: |
        kubectl get deployments
        kubectl get svc
        kubectl get configmap
        kubectl get secret
        kubectl get pods
