name: Blue-Green Deploy

on:
  workflow_dispatch:
#  push:
#    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create kind cluster
      uses: helm/kind-action@v1

    - name: Deploy Blue (current)
      run: kubectl apply -f k8s/blue/

    - name: Deploy Green (new)
      run: kubectl apply -f k8s/green/

    - name: Create Service
      run: kubectl apply -f k8s/service.yaml

    - name: Switch traffic to Green
      run: |
        kubectl patch service nginx-service \
        -p '{"spec":{"selector":{"app":"nginx","version":"green"}}}'

    - name: Verify rollout
      run: kubectl get pods
