name: K8s Validate

on:
  workflow_dispatch:
#  push:
#    branches: [dev, staging, main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Validate manifests
      run: |
        kubectl apply --dry-run=client -f k8s/
