name: K8s Deploy (kind)

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  k8-labs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Create Kind Cluster
      uses: helm/kind-action@v1

    - name: Set Environment
      run: |
        if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
          echo "ENV=dev" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF##*/}" == "staging" ]]; then
          echo "ENV=staging" >> $GITHUB_ENV
        else
          echo "ENV=prod" >> $GITHUB_ENV
        fi

    - name: Create Namespace
      run: kubectl create namespace $ENV || true

    - name: Deploy
      run: kubectl apply -f k8s/$ENV/

    - name: Verify
      run: kubectl get pods -n $ENV
