name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-docker-build:
    uses: ./.github/workflows/docker-build-reusable.yml

    with:
      image_name: niketrana/github-actions-app
      image_tag: latest

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
