name: Multiple Needs Fail Lab

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1 Success
        run: echo "Job 1 passed"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2 Fail
        run: exit 1

  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: echo "This is Job 3"
